language: java
jdk:
 - oraclejdk8
after_success:
  - bash <(curl -s https://codecov.io/bash)
 
notifications:
  email:
    recipients:
      - fodorpapbalazsdev@gmail.com
    on_success: always # default: change
    on_failure: always # default: always
